version: '3.0'

services:

  qgis-desktop:
    image: qgis-desktop:3.4.5
    # platform: linux/x86_64
    build:
      context: .
      dockerfile: Docker/qgis_ltr/Dockerfile

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Allow GUI application to run in docker
      - .:/home/nens/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox
      - qgis-settings:/home/nens/.local/share/QGIS/
    environment:
      - DISPLAY=unix${DISPLAY}
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
    cap_add:
      - SYS_PTRACE

volumes:
  qgis-settings:
